packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
  - "database"
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
